{{- if .Values.caddyingresscontroller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Values.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.caddyingresscontroller.serviceAccount.labels }}
{{ toYaml .Values.caddyingresscontroller.serviceAccount.labels | indent 4 }}
{{- end }}
{{- if .Values.caddyingresscontroller.matchLabels }}
{{ toYaml .Values.caddyingresscontroller.matchLabels | indent 4 }}
{{- end }}
  name: {{ .Values.serviceAccountName }}
{{- end }}