apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-global-options
  namespace: caddy-system
data:
  acme-ca: https://acme-staging-v02.api.letsencrypt.org/directory
  email: test@example.com
  debug: "false"
