apiVersion: v2
name: caddy-ingress-controller
home: https://github.com/caddyserver/ingress
description: A helm chart for the Caddy Kubernetes ingress controller
icon: https://caddyserver.com/resources/images/caddy-circle-lock.svg
type: application
version: 1.2.1
appVersion: "v0.2.1"
keywords:
  - ingress-controller
  - caddyserver
sources:
  - https://github.com/caddyserver/ingress
maintainers:
  - name: mavimo
    url: https://github.com/mavimo
  - name: embraser01
    url: https://github.com/embraser01
